### ISSUE TITLE
`holdSubject` should buffer inputs even without listeners

### ISSUE THREAD

**Issue by ntilwalli** [mostjs-community/most-subject#22]
I feel like https://github.com/mostjs-community/most-subject/blob/master/src/HoldSubjectSource.ts#L30 should be moved above the `if(!this.isActive...)` line.  Currently the `@cycle/storage` driver emits item streams using a `startWith`.  That item is currently pushed into a basic most Subject using `adapt` during the initial wiring of the stream, which means the values that are sent are being dropped since there are no active listeners.

I hacked the `most-adapter` code to start using a `holdSubject` to see if that fixed things but it doesn't because `holdSubject` doesn't buffer the value that is sent into it unless it has listeners.  I think that's wrong. I think a hold subject should buffer values sent in even when there are no listeners.  The purpose of a holdSubject is "value over time" so shouldn't it maintain the values it receives so the first listener gets a value immediately without having to wait for a follow-on emission?

**Comment by ntilwalli** [comment]
I propose the function should look something like this:
```
    HoldSubjectSource.prototype.next = function (value) {
        if (this.scheduler === void 0) {
          return;
        }

        var time = this.scheduler.now();
        this.buffer = util_1.dropAndAppend({ time: time, value: value }, this.buffer, this.bufferSize);

        if (!this.active) {
            return;
        }

        this._next(time, value);
    };
```

**Comment by brandonpayton** [comment]
This is a recent change that occurred when I submitted a PR to fix another issue. It was something we needed to discuss that I probably should have been clearer about. I did it that way because it is [currently how most/hold behaves](http://www.webpackbin.com/VydeJtGOb), but maybe it is something we need to correct. Your expectation is more intuitive to me personally.

@TylorS and @briancavalier What are your thoughts?

**Comment by briancavalier** [comment]
I'm not super familiar with the current most-subject implementation, but I'll try to offer some perspective.

One essential difference between `holdSubject` and `@most/hold` stems from the fact that streams (non-subjects) only have a producer when they also have a consumer, whereas subjects always have a producer--the party who created the subject or another party to whom the subject has been given--even when there is no consumer.  The consequence is that streams don't have to deal with the (often tricky) situation of producing events when there is no consumer, and subjects do.

So, I think it's perfectly reasonable for `holdSubject` to do something different from `@most/hold` in order to handle that difference in an intuitive way.  It does seem like `holdSubject` would need to buffer events even when there's no consumer.

I hope that's helpful!

**Comment by TylorS** [comment]
This has been fixed :+1:
